# zips SOURCE_DIR and generates a c++ source and header embedding the bytes under NAMESPACE

if(NOT SOURCE_DIR OR NOT OUTPUT_CPP OR NOT OUTPUT_HPP OR NOT NAMESPACE)
    message(FATAL_ERROR "embed-resources.cmake requires SOURCE_DIR, OUTPUT_CPP, OUTPUT_HPP, NAMESPACE")
endif()

if(NOT EXISTS "${SOURCE_DIR}")
    message(FATAL_ERROR "embed-resources.cmake: SOURCE_DIR does not exist: ${SOURCE_DIR}")
endif()

# create the zip archive
set(ZIP_FILE "${OUTPUT_CPP}.zip")
execute_process(
    COMMAND ${CMAKE_COMMAND} -E tar cf "${ZIP_FILE}" --format=zip -- .
    WORKING_DIRECTORY "${SOURCE_DIR}"
    RESULT_VARIABLE ZIP_RESULT
)

if(NOT ZIP_RESULT EQUAL 0)
    message(FATAL_ERROR "embed-resources.cmake: failed to create ZIP from ${SOURCE_DIR}")
endif()

# read the zip as hex
file(READ "${ZIP_FILE}" ZIP_HEX HEX)
file(SIZE "${ZIP_FILE}" ZIP_SIZE)

# format as a c byte array like 0xAB,0xCD
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," HEX_ARRAY "${ZIP_HEX}")

# generate .cpp
file(WRITE "${OUTPUT_CPP}"
"// generated by embed-resources.cmake, do not edit
#include <cstddef>

namespace ${NAMESPACE} {

alignas(16) static const unsigned char resource_data[] = {${HEX_ARRAY}};

const unsigned char* getData() { return resource_data; }
size_t getSize() { return ${ZIP_SIZE}; }

} // namespace ${NAMESPACE}
")

# generate .hpp
file(WRITE "${OUTPUT_HPP}"
"// generated by embed-resources.cmake, do not edit
#pragma once
#include <cstddef>

namespace ${NAMESPACE} {

const unsigned char* getData();
size_t getSize();

} // namespace ${NAMESPACE}
")

# cleanup
file(REMOVE "${ZIP_FILE}")

message(STATUS "Embedded ${ZIP_SIZE} bytes from ${SOURCE_DIR} into ${NAMESPACE}")
